low_level_categories = {'Automobile' : ['Auto', 'Autoindustrie', 'Automobilindustrie', 'Automobilzulieferer',
                                        'Elektromobilität', 'Dieselskandal', 'Diesel', 'A8', 'Lkw'],
                        'Bildung' : ['Schule', 'Schulen', 'Schüler', 'Studie', 'Bildung', 'Unterricht', 'Lehrer',
                                     'Distanzunterricht', 'Ausbildung', 'Universität', 'Abitur', 'Wechselunterricht',
                                     'Hochschule', 'Studium', 'Präsenzunterricht'],
                        'Finanzen' : ['Euro', 'Nikkei', 'Deutsche Bank', 'EZB', 'Finanzen', 'Geld', 'Insolvenz',
                                      'Steuern', 'Geldpolitik', 'Bilanz', 'Banken', 'Fed', 'US-Notenbank',
                                      'Gold', 'Commerzbank', 'BaFin', 'Rente', 'Zinsen'],
                        'Elektronik' : ['Smartphone', 'Metall- und Elektroindustrie', 'Handy', 'Fans'],
                        'Fußball' : ['Fußball', 'FC Bayern München', 'Bundesliga', '3. Liga', '2. Bundesliga', 
                                     'DFB', 'Champions League', '1. FC Nürnberg', 'Hansi Flick', 'FC Augsburg',
                                     'TSV 1860 München', 'SSV Jahn Regensburg', 'Fußball-EM', 'Würzburger Kickers',
                                     'Europameisterschaft', 'SpVgg Greuther Fürth', 'FC Ingolstadt 04', 
                                     'Joachim Löw', 'DFB-Pokal', 'Türkgücü München', 'SpVgg Unterhaching',
                                     'FC Bayern München II', 'Frauenfußball', 'Thomas Müller', 'UEFA', 
                                     'FC Bayern Frauen', 'Robert Lewandowski', 'Bundestagswahl 2021', 'DFL', 
                                     'Borussia Dortmund', 'Manuel Neuer', 'Heiko Herrlich', 's.Oliver Würzburg',
                                     'Fußball-Bundesliga', 'Karl-Heinz Rummenigge', 'Regionalliga Bayern',
                                     'Fußball-Europameisterschaft', 'Rainer Koch', 'Amateurfußball', 'BFV',
                                     'Deutscher Fußball-Bund'],
                        'Gesellschaft' : ['Urlaub', 'Neustart', 'Ernährung', 'Alkohol', 'Party', 'Spenden', 'Jubiläum',
                                          'Tod', 'Müll', 'Arbeitsplätze', 'Familie', 'Ferien', 'Gesellschaft', 'Bier',
                                          'Tote', 'Ehrenamt', 'Bergwacht', 'Pflegeheim', 'Schlachthof', 'Hotel', 
                                          'Gedenken', 'Tradition', 'Wohnen', 'Sommerferien', 'Garten', 'Alkoholverbot',
                                          'Soziales', 'Freibad', 'Supermarkt', 'Trauer', 'Bauarbeiten', 'Fleisch',
                                          'Umfrage', 'Pendler', 'Architektur', 'Haushalt', 'Geburtstag', 'Ausflug', 
                                          'Neubau', 'Mode', 'Restaurant', 'Einkaufen', 'Biergarten', 'Hotels',
                                          'Essen', 'Gaststätten', 'Schließung', 'Pfingsten', 'Förderung', 
                                          'Camping', 'Armut', 'Wasserwacht', 'Unglück', 'Fleischindustrie',
                                          'Feiertag', 'Straßenbau', 'Seniorenheim', 'Senioren', 'Eltern', 'Altenheim',
                                          'Altenpflege', 'Fische'],
                        'Gesundheit' : ['Gesundheit', 'Medizin', 'Krankenhaus', 'Pflege', 'Gesundheitsministerium',
                                        'Drogen', 'Infektionsschutzgesetz', 'Gesundheitsamt', 'Intensivstation',
                                        'Fitnessmagazin', 'Trinkwasser', 'Klinik', 'Verletzte', 'Krankheit', 'Ärzte',
                                        'Pflegekräfte', 'Ansteckung', 'Medikamente', 'Krebs', 'Hotspots', 'WHO', 
                                        'Krankenhäuser', 'Hygienevorschriften', 'LGL', 'Lothar Wieler', 'Klinikum', 
                                        'Geburt', 'Hausärzte', 'Geflügelpest', 'Depression', 'Aerosole', 'Arzt',
                                        'Grippe', 'Stiko', 'Apotheke', 'Patienten', 'Vogelgrippe', 'Impfung', 'RKI', 
                                        'Robert-Koch-Institut', 'Infektion', 'Präsenzunterricht',
                                        'Robert Koch-Institut'],
                        'Justiz' : ['Justiz', 'Hof', 'Urteil', 'Kriminalität', 'Staatsanwaltschaft', 'Gericht',
                                    'Missbrauch', 'Sexueller Missbrauch', 'Landratsamt', 'Klage', 'Landgericht', 
                                    'Bayerischer Verwaltungsgerichtshof', 'Bundesverfassungsgericht',
                                    'Maskenaffäre', 'Bundesgerichtshof', 'BGH'],
                        'Polizei' : ['Kriminalität', 'Gericht', 'Sexueller Missbrauch'],
                        'Katastrophe' : ['Brand', 'Hochwasser', 'Verkehrsunfall', 'Unwetter', 'Überschwemmungen',
                                         'Gewitter', 'Hochwasserschutz', 'Sachschaden'],
                        'Kinder' : ['Kinder', 'Jugendliche', 'Kita', 'Grundschule', 'Kindergarten', 'Kindesmissbrauch',
                                    'Kitas', 'Baby', 'Kinderpornografie', 'Kinderbetreuung'],
                        'Konjunktur' : ['Verdi', 'Arbeitsmarkt', 'Baustelle', 'Arbeit', 'Konjunktor', 
                                        'Konjunktur', 'Arbeitslosigkeit',
                                        'Mieten', 'BIP', 'Inflation', 'Versicherung', 'Deutsche Post', 'Startup', 'Zoll',
                                        'Arbeitslosenzahlen', 'Start-Up', 'Konjunktursorgen', 'Verbraucherschutz',
                                        'Konjunkturpaket'],
                        'Kultur' : ['Tourismus', 'Kultur', 'Kino', 'Gastronomie', 'Musik', 'Kunst', 'Weihnachten',
                                    'Literatur', 'Film', 'Theater', 'Reisen', 'Ausstellung', 'Freizeit', 'Museum',
                                    'Geschichte', 'kinokino', 'Wandern', 'Lebensmittel', 'Kontrovers', 'Oktoberfest',
                                    'Film und Serie', 'Kritik', 'Handwerk', 'Künstler', 'George Floyd', 'Silvester',
                                    'Volksfest', 'Zuschauer', 'Buch', 'Hollywood', 'Konzert', 'Festival', 'Oper',
                                    'Albumkritik', 'Schauspieler', 'Fasching', 'Auszeichnung', 'Schausteller',
                                    'Reisewarnung', 'Dehoga', 'Kabarett', 'Bücher', 'Pop', 'Lesen', 'Kulturhauptstadt',
                                    'Album', 'Richard Wagner', 'Öffnung', 'Veranstaltungen', 'Kultusministerium'],
                        'Landwirtschaft' : ['Landwirtschaft', 'Weiden', 'Bauern', 'Landwirte', 'Erntehelfer'],
                        'Nachrichten' : ['Rundschau', 'Bayern 2', '#faktenfuchs', 'Bayernthema', 'radioWelt', 'Medien',
                                         '#Faktenfuchs', 'B5 aktuell', 'Tagesgespräch', 'ARD', 'Fernsehen', 'BR24Live', 
                                         'Sternstunden', 'Possoch klärt', 'Journalismus', 'Podcast', 'mehr/wert', 
                                         'ZDF', 'Pressefreiheit', 'ARD-WIEN', 'Tagesschau', 'ARD-alpha', 'STATIONEN'],
                        'Netzwelt' : ['Facebook', 'Internet', 'Datenschutz', 'Twitter', 'Instagram', 'App', 'Social Media',
                                      'Streaming', 'Bitcoin', 'TikTok', 'Fake News', 'Netflix', 'Soziale Netzwerke',
                                      'Youtube', 'WhatsApp', 'Online', 'Soziale Medien', 'Mobilfunk'],
                        'Personen' : ['Demonstration', 'Flüchtlinge', 'Rassismus', 'Protest', 'Streik', 'Warnstreik', 'Antisemitismus',
                                      'Verschwörungstheorien', 'Frauen', 'Ausgangssperre', 'Proteste', 'Zweiter Weltkrieg', 
                                      'Streit', 'Anschlag', 'Querdenken', 'Demokratie', 'Juden', 'BRK', 'Migration', 'Flucht',
                                      'Hilfe', 'Asylbewerber', 'Holocaust', 'Homosexualität', 'Diskriminierung',
                                      'Körperverletzung', 'Petition', 'Integration', 'Menschen mit Behinderung', 
                                      'Inklusion', 'Demonstrationen', 'Black Lives Matter', 'Migranten', 'Abschiebung',
                                      'Gleichberechtigung', 'Kundgebung', 'Bürgerinitiative', 'Menschenrechte', 'Absage',
                                      'Hubschrauber', 'Caritas', 'Geflüchtete', 'Seenotrettung', 'Terrorismus', 
                                      'Rettungskräfte', 'Rettungshubschrauber', 'Bayerisches Rotes Kreuz', 'Obdachlose', 
                                      'Nationalsozialismus'],
                        'Politik' : ['Markus Söder', 'CSU', 'Donald Trump', 'Angela Merkel', 'SPD', 'Joe Biden',
                                     'Bundestagswahl', 'Grüne', 'Jens Spahn', 'Freie Wähler', 'AfD', 'CDU', 
                                     'Hubert Aiwanger', 'Politik', 'Rechtsextremismus', 'FDP', 'Bundestag', 'Armin Laschet',
                                     'Michael Piazolo', 'Landtag', 'Klaus Holetschek', 'Horst Seehofer', 'Joachim Herrmann',
                                     'Nationalsozialismus', 'Brexit', 'Olaf Scholz', 'US-Wahl', 'Melanie Huml', 
                                     'Kanzlerkandidatur', 'Bernd Sibler', 'Kultusministerium', 'Wahl', 
                                     'Bayerischer Landtag', 'Alexej Nawalny', 'Boris Johnson', 'US-Präsidentschaftswahl', 
                                     'CDU/CSU', 'Die Grünen', 'Andreas Scheuer', 'Verfassungsschutz', 'Annalena Baerbock',
                                     'Dieter Reiter', 'US-Präsident', 'Parteitag', 'Annegret Kramp-Karrenbauer', 
                                     'Heiko Maas', 'Wladimir Putin', 'Ursula von der Leyen', 'Alexander Lukaschenko',
                                     'Sebastian Kurz', 'Wahlkampf', 'Frank-Walter Steinmeier', 'Bündnis 90/Die Grünen',
                                     'Linke', 'Kommunalwahl', 'Peter Altmaier', 'Hubertus Heil', 'Thorsten Glauber', 
                                     'Kommunalpolitik', 'Karl Lauterbach', 'Münchner Runde', 'Robert Habeck',
                                     'Kommentar', 'NSU', 'Opposition', 'Benjamin Netanjahu', 'Die Linke', 
                                     'Friedrich Merz', 'Julia Klöckner', 'Präsidentschaftswahl', 'Heinz-Peter Meidinger',
                                     'Kabinett', 'US-Wahlkampf', 'Emmanuel Macron'],
                        'Polizei' : ['Polizei', 'Polizeimeldung', 'Mord', 'Gewalt', 'Ermittlungen', 'Betrug', 'Fahndung',
                                     'Messerattacke', 'Festnahme', 'Bundespolizei', 'Diebstahl', 'Terror', 'Mordprozess', 
                                     'Vergewaltigung', 'Polizeieinsatz', 'Kriminalpolizei', 'Polizeigewalt', 
                                     'Brandstiftung', 'Kripo', 'Fliegerbombe', 'Totschlag', 'Einbruch', 'Angriff', 
                                     'Zeugen', 'Großeinsatz', 'Vermisstensuche', 'Gefängnis', 'Hacker', 'Vermisste', 
                                     'Messerangriff', 'Hackerangriff', 'Cybercrime', 'Tötungsdelikt', 'Schleuser',
                                     'Schlägerei'],
                        'Regierung' : ['Prozess', 'Stadtrat', 'Bundesregierung', 'Bundeswehr', 'Grenze', 'Grenzkontrollen',
                                       'Staatsregierung', 'Sanierung', 'Ausgangsbeschränkung', 'Kontaktbeschränkungen',
                                       'Oberbürgermeister', 'Sicherheit', 'Kommunen', 'Bürgermeister', 'Bürgerentscheid',
                                       'Bußgeld', 'Kontrollen', 'Sperrung', 'IHK', 'Rathaus', 'Verwaltungsgericht',
                                       'Denkmalschutz', 'Öffentlicher Dienst', 'Korruption', 'Razzia', 'Waffen', 
                                       'Landrat', 'Militär', 'Untersuchungsausschuss', 'THW', 'LGL',
                                       'Landesamt für Gesundheit und Lebensmittelsicherheit', 'Truppenabzug', 'NATO', 'Zollstreit'],
                        'Religion' : ['Religion', 'Kirche', 'Katholische Kirche', 'Evangelische Kirche', 'Glaube',
                                      'Gottesdienst', 'Judentum', 'Islam', 'Papst Franziskus', 'Muslime', 'Papst', 
                                      'Synagoge'],
                        'Sport' : ['Sport', 'Basketball', 'Nationalmannschaft', 'BBL', 'Olympia', 'FC Bayern Basketball',
                                   'Basketball-Bundesliga', 'Brose Bamberg', 'Olympische Spiele', 'Tokio 2020',
                                   'Tennis', 'Schwimmen', 'Radsport', 'medi bayreuth', 'Formel 1', 'Handball', 'Motorsport',
                                   'Transfer', 'Breitensport', 'Schwimmbad', 'Blickpunkt Sport', 'Markus Eisenbichler', 
                                   'Gymnasium', 'Geisterspiele', 'Karl Geiger', 'Doping', 'Sebastian Vettel'],
                        'Tierwelt' : ['Tiere', 'Tierschutz', 'Artenschutz', 'Hunde', 'Vögel', 'Wildtiere', 
                                      'Landesbund für Vogelschutz', 'Wolf', 'Bienen', 'Zoo', 'Haustiere', 'Pferde', 
                                      'Tierheim', 'Schweine', 'Tierwohl', 'Bund Naturschutz'],
                        'Transport' : ['Verkehr', 'Bahn', 'Autobahn', 'Fahrrad', 'ÖPNV', 'Deutsche Bahn',
                                       'A3', 'Mobilität', 'Motorrad', 'Stau', 'A9', 'Flughafen', 'Nahverkehr',
                                       'Bus', 'Bahnhof', 'Öffentlicher Nahverkehr', 'Flugverkehr', 'Radfahrer',
                                       'S-Bahn', 'Zug', 'Fahrradfahrer', 'Lastwagen', 'Flugzeug', 'Motorradfahrer',
                                       'Straßenverkehr', 'ICE'],
                        'Umwelt' : ['Klimawandel', 'Wald', 'Umwelt', 'Klimaschutz', 'Naturschutz', 'Wetter', 'Natur', 'Umweltschutz',
                                    'Bayerischer Wald', 'Schnee', 'Winter', 'Regen', 'Sommer', 'Bund Naturschutz',
                                    'Starkregen', 'Wasser', 'Klima', 'Hitze', 'Trockenheit', 'Fridays for Future', 'LBV', 
                                    'Berge', 'Wiesn', 'Insekten', 'Bäume', 'Artenvielfalt', 'Pflanzen', 'Erderwärmung',
                                    'Deutscher Wetterdienst', 'Fluss', 'Hagel', 'Ökologie', 'Treibhausgase'],
                        'Unfall' : ['Feuerwehr', 'Unfall', 'Feuer', 'tödlicher Unfall', 'Explosion', 'Raser',
                                    'Evakuierung', 'Rettung', 'Unfälle', 'Notbremse', 'Badeunfall', 'Sachschaden'],
                        'Wintersport' : ['Wintersport', 'Ski Alpin', 'Eishockey', 'Biathlon', 'Skispringen', 
                                         'DEL', 'Deutsche Eishockey-Liga', 'Skifahren', 'Straubing Tigers',
                                         'Rodeln', 'Langlauf'],
                        'Wirtschaft' : ['Wirtschaft', 'Einzelhandel', 'IG Metall', 'Gewerkschaft', 'Union', 
                                        'Kurzarbeit', 'Handelskonflikt', 'Stellenabbau', 'Nachhaltigkeit',
                                        'Tarifverhandlungen', 'Ölpreis', 'Handel', 'Handelsstreit', 'Verbraucher',
                                        'Immobilien', 'Wirtschaftswachstum', 'Brauchtum', 'Industrie', 'Brauerei',
                                        'Online-Handel', 'Holz', 'Geschäfte', 'DGB'],
                        'Wissen' : ['Datenschutz', 'Forschung', 'Wissenschaft', 'Digitalisierung', 
                                    'Energiewende', 'Weltraum', 'Energie', 'Raumfahrt', 'CO2', 'Astronomie', 
                                    'Faktencheck', 'Luftfahrt', 'Archäologie', 'Statistik', 
                                    'Künstliche Intelligenz', 'Psychologie', 'Strom', 'Windkraft', 
                                    'Erneuerbare Energien', 'Atomkraft', 'ifo-Institut', 'Wasserstoff',
                                    'Treibhausgase', 'Atommüll', 'Weltall', 'Photovoltaik', 'NASA'],
                        'Coronavirus' : ['Coronavirus', 'Corona', 'Corona-Krise', 'Covid-19', 'Pandemie', 
                                         'Lockdown', 'Coronakrise', 'Corona-Pandemie', 'RKI', 'Robert-Koch-Institut',
                                         'Impfung', 'SARS-CoV-2', 'Maskenpflicht', '7-Tage-Inzidenz', 'Impfstoff',
                                         'Corona-Maßnahmen', 'Corona-Test', 'Corona-Impfungen',
                                         'Corona-Impfstoff', 'Quarantäne', 'Neuinfektionen', 'Lockerungen',
                                         'Liveticker', 'Impfzentrum', 'Inzidenzwert', 'Biontech', 
                                         'Corona-Mutation', 'Infektion', 'Homeoffice','Homeschooling', 
                                         'AstraZeneca', 'Schnelltest', 'FFP2-Masken', 'Sieben-Tage-Inzidenz', 
                                         'Corona-Regeln', 'Corona-Lockerungen', 'Mund-Nasen-Masken'
                                         'Ausgangssperre', 'Teil-Lockdown', 'Coronatest', 'Ausgangsbeschränkung',
                                         'Corona-Virus', 'Corona-Warn-App', 'Kontaktbeschränkungen','Testpflicht', 
                                         'Intensivstation', 'Hygienekonzept', 'Virus', 'Präsenzunterricht', 
                                         'Robert Koch-Institut','Hygiene', 'Infektionszahlen', 'Robert Koch-Institut',
                                         'Reiserückkehrer', 'Abstandsregelung', 'Masken', 'Moderna', 
                                         'Querdenken','Todesfälle', 'Astrazeneca', 'R-Wert', 'Risikogebiet', 
                                         'Corona-Auflagen', 'Intensivbetten', 'Delta-Variante', 'Corona-Impfung', 
                                         'Pfizer', 'Test', 'Mund-Nasen-Schutz', 'PCR-Test', 'Corona-App', 
                                         'Infektionsschutz', 'Corona-Demo', 'Corona-Teststation', 'Impfpflicht', 
                                         'Impfzentren, ''Sars-CoV-2-Virus', 'Corona-Schnelltest'],
                        'Börse' : ['Börse', 'Aktien', 'DAX', 'Euro', 'Dow Jones', 'MDAX', 'Nasdaq', 'B5 Börse', 'Wall Street', 'Nikkei']}